### PR TITLE
Add support to R.swift

### PR DESCRIPTION
**Pull request by lvpengwei**
#3

### CODE REVIEW

**Comment by onevcat** [comment]
@lvpengwei Thanks for the PR. And terribly sorry for the delay of reply!

For R.swift, if I am right, it is also very common to use a CLT to generate the image definition from Assets folder. I guess there might be some conflicting when you want to add an image to your project. You need to let R.swift generate a typed variable for using it in your code. However, if this PR applied, the added images will be removed before you get a chance to write`R.image.xxx`. Am I correct? (I personally not quite familiar with R.swift since I am not using it every day).

If so, I am afraid that supporting for R.swift might cause quite some confusing and unexpected behaviors. Or is there a good way to handle that?

Thanks again for considering contributing!

**Comment by lvpengwei** [comment]
你是对的，两者会有冲突。我是把 rswift 放在 Build Phases 里，在功能开发完，提交到主分支之前再执行 FengNiao（ignore R.generated.swift）。

**Comment by onevcat** [comment]
@lvpengwei Thanks for the clarification. I guess we'd better not merge it since there might be some non-trivial side effects, depending on the way of using FengNiao.

Anyway, thanks for this PR and it is a good reference for others.

**Comment by 913868456** [comment]
> 你是对的，两者会有冲突。我是把 rswift 放在 Build Phases 里，在功能开发完，提交到主分支之前再执行 FengNiao（ignore R.generated.swift）。

项目调用图片的时候用的是R.generated.swift中生成的图片调用方法， 默认的话R会生成所有图片的调用方法吧？，请问下您是如何在项目中移除未使用的图片资源？

**Comment by lvpengwei** [comment]
> > 你是对的，两者会有冲突。我是把 rswift 放在 Build Phases 里，在功能开发完，提交到主分支之前再执行 FengNiao（ignore R.generated.swift）。
> 
> 项目调用图片的时候用的是R.generated.swift中生成的图片调用方法， 默认的话R会生成所有图片的调用方法吧？，请问下您是如何在项目中移除未使用的图片资源？

这个 pr 的代码修改了图片的匹配规则，来支持 R.image.xxx()，然后命令行扫描的时候忽略 R.generated.swift 文件。

**Pull request closed without merging**
