### PR TITLE
Add macOS app

### PR DESCRIPTION
**Pull request by ldakhoa**
## What's new?
- Make `FengNiaoKit` publish
- Make `FileInfo` initialize public
- Format some lines of code like empty lines, and double spaces,...
- Add a macOS app to visualize unused resources

## macOS features
- Sort the unused resources table based on `File Name`, `Size`, or `Full Path`
- Select file(s) to delete or delete all unused resources
- Export and download CSV
image

## Misc
**App icon**
I have cropped the image from [logo.png](https://github.com/onevcat/FengNiao/blob/master/logo.png). You can give me an original logo without the text, I can make a new logo based on this. Currently, this is how it looks on the dock
image

**Signing**
- I have set bundle identifier `com.onevcat.fengniao`, you can edit as you want
- I have turned on `Hardened Runtime` to test the release app of my apple dev account, you can turn it off when release it :smile:

**Notes**
- About the progress view in the delete view, I have a hack to let it run when deleting files
- To test the app, just open `App/fengniao.xcodeproj` and run the scheme `FengNiao-macOS`

### CODE REVIEW

**Comment by SweetHouse** [comment]
good job

**Comment by onevcat** [comment]
@ldakhoa Wow, great. I never expected you also contain the app here. Can I also create a link to your repo and app in the Readme?

**Comment by ldakhoa** [comment]
@onevcat Is it possible to merge this PR? If we can, I will archive my repo and you don't need to link to it, or if you want to separate the CLI and macOS app, you can link to my repo 😄

**Comment by onevcat** [comment]
@ldakhoa 

> Is it possible to merge this PR?

Sure, of course. There is no blocker for merging it!

However, I initially just expected some adjustment of FengNiaoKit (exposing some interfaces necessary for you and some fixes to allow your app work), instead of a whole app here in this repo. 

Since you took the effort to create the app and own it, I want to ask for your choice. In fact, you could polish and release the app to the AppStore (even to make some profit, if you want). So I don't think I am the correct person to make the decision.

Please let me know your opinion!

**Comment by ldakhoa** [comment]
@onevcat 
> Sure, of course. There is no blocker for merging it!

Cool

> However, I initially just expected some adjustment of FengNiaoKit (exposing some interfaces necessary for you and some fixes to allow your app to work), instead of a whole app here in this repo.

To be honest, I think if we can merge here it will be great because this repo is popular, if someone wants to use it, they will have two options, install and use CLI or download the app directly in your repo without navigating to my repo, then read the readme again to download it. This will make some extra effort to use.

Anyway, just my opinion, I'm okay with both ways, if you want to separate the app, just adjust the FengNiaoKit, and I will change the dependency again :D

**Pull request merged**
